/*--------------------------------------------------------------------------
 * This file is autogenerated from config.h.in 
 * during the cmake configuration of your project. If you need to make changes
 * edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/
#pragma once
#include <string>

//PROJECT NAME
const std::string PACKAGE_NAME = "OpenSettlers";

//VERSION NUMBER
const std::string VERSION_MAJOR = "0";
const std::string VERSION_MINOR = "0";
const std::string VERSION_PATCH = "0";
const std::string VERSION = "0.0.0";

//GIT INFO
const std::string GIT_SHA1 = "";
const std::string GIT_DATE = "";
const std::string GIT_COMMIT_SUBJECT = "";
